### ISSUE TITLE
Set up Meta Drive as a special page

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Wordpress#54]
Meta Drive enables an admin to embed a google drive interace into an iframe. This is great because the native iframe embed has been very poorly integrated. The goal is to create a new template page called "Metadrive" that allows one to embed a metadrive page as a full page iframe.

**Comment by nowned** [comment]
Just to clarify, you basically want an HTML page template that has no other styles/content on it, and so your Wordpress content will override the whole page? So it would end up being a full page iFrame embed

**Comment by petergault** [comment]
Yep that's right. I've detailed this in issue 55

**Comment by petergault** [comment]
This is what the meta-drive page will look like:

This site will be iframed: 
https://sites.google.com/a/quill.org/metadrive/
