### ISSUE TITLE
iFrame Generic Template page

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Wordpress#55]
- The goal here is to set up a template page called "iframe". This template will be used for pages that iframe another site. 
- The template should be set up so that the content is 100% width of the screen and 800 pixels tall. 
- The title of the pages ("issues") should not be displayed on this template. 

For example, on this page, the waffle dashboard should be shown taking up the whole page width. 
See this page: http://community.quill.org/teams/quill-writer/issues/

**Comment by nowned** [comment]
Template is in place now and setup for that page!

http://community.quill.org/teams/quill-writer/issues/
