### ISSUE TITLE
Add the "Activity" link to the Team's Menu Bar. 

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Wordpress#57]
The default page for each team is this:
http://community.quill.org/teams/quill-writer

How can this page be included as a default link on the navigation bar for that team? Each team should automatically have the link called "Members" 

If this is a pain to do, I don't mind creating a page for each team. How would the page be associated with that link though?

**Comment by nowned** [comment]
Hey Peter,

Sorry, i'm confused by what you are trying to accomplish. Could you explain it in more detail?

Thanks!

**Comment by petergault** [comment]
Hi Matt,

Sorry for the confusion. When you click on a new team, you see the page that shows the activity feed for that page. The issue is that you don't see a link to it on the team's menu bar. There should be a button called "Activity" (previously I was stating it should be members). Here are the comparison screenshots:

# Current Site
![current-community-page-no-default](https://cloud.githubusercontent.com/assets/3667179/7449031/01d19066-f1e0-11e4-963e-bd6fddb72da1.png)

# With the "Activity" Button
![page-with-activity-as-default](https://cloud.githubusercontent.com/assets/3667179/7449033/07af5e28-f1e0-11e4-887c-7d00b1dbdcbc.png)

**Comment by nowned** [comment]
Added now!
