### ISSUE TITLE
Install Google Drive Viewer

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Wordpress#65]
We will use this plug in to enable people to view files from Google Drive. 

https://wordpress.org/plugins/googledrive-folder-list/

As part of this update, Peter should completely remove all hooks to meta-drive.

**Comment by petergault** [comment]
If this app isn't a solid app, we can also look into this: http://codecanyon.net/item/useyourdrive-google-drive-plugin-for-wordpress/6219776

**Comment by nowned** [comment]
Installed now!
