### ISSUE TITLE
Priority: Update the Navigation to match the rest of Quill

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Wordpress#71]
Update Navigation to Match the rest of the site

![quill_wordpress_nav](https://cloud.githubusercontent.com/assets/3667179/6070772/6b8c1bce-ad5d-11e4-90e8-51459d3b65fd.png)

Full Sized: 
https://drive.google.com/file/d/0B-r431ws0zjXb3ZQQTkxd2hLVkU/view?usp=sharing

The Quill navigation needs to match the rest of the site. Here are the following steps:

1. Swap the Logo. The logo is attached here: 
https://drive.google.com/file/d/0B-r431ws0zjXb01vZk5DeVhqRk0/view?usp=sharing
2. Change the font to the TypeKit font Adelle Sans. To set up TypeKit please go to TypeKit.com and sign in with the username provided in the email. This font should be applied everywhere, Adelle Sans is the only font we should be using from now on. 
3. The color for the background is: 00c2a2 
4. The Discover link should link to quill.org/about. 
5. Hopefully you can get the spacing of the header to match the rest of the Quill site. To see the current spacing please go to quill.org and sign in with the username: Student, password: Student. 
This will give you the dimensions you need for the header.

**Comment by nowned** [comment]
A basic implementation of this is in now, some spacing issues and sizing will be tweaked later this week!
