### ISSUE TITLE
Add Favicon to Wordpress

### ISSUE THREAD

**Issue by tomcalabrese** [empirical-org/Empirical-Wordpress#75]
We want to add the new favicon to wordpress, so all of the favicons are consistent no matter what page a user is on. 

[Favicon](https://drive.google.com/file/d/0B1RagCbDewKWRHRpX01CcFBmQnM/view?usp=sharing)

**Comment by nowned** [comment]
Favicon updated in c901619daf551d996fc93fb9938f0cbb2735b850
