### ISSUE TITLE
Turn the link in the active page into a button

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Wordpress#77]
On the Quill Discover pages, the link for the currently selected page is shown in a grey box. For the Community pages, these pages should also show a grey box for the currently selected page. 
![screen shot 2015-05-03 at 10 03 41 pm](https://cloud.githubusercontent.com/assets/3667179/7449050/732f9492-f1e0-11e4-8b29-823cc8cb8fe3.png)

**Comment by nowned** [comment]
Done now!
