### ISSUE TITLE
Don't show the title on the default page template

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Wordpress#78]
On the default page template we are currently showing the title of the page. This is redundant info because it is already in the menu bar. Can we please remove it from this template? 

For example, this page should not have "OSS Supporters" listed at the top:
http://community.quill.org/teams/quill-lms/open-source-supporters/

**Comment by nowned** [comment]
Fixed in 3329c4063621481d07b67ce8ae8630537d2d417c
