### ISSUE TITLE
Change the column size on the default page template

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Wordpress#79]
The column size should be changed so that it aligns with the logo on the left hand side and ends approximately on the right hand side where the "fundraising" tab ends. Currently it extends to the end of the page. 

The text should reflect the "red" area where it currently is in the purple. 

![community page dimensions](https://cloud.githubusercontent.com/assets/3667179/7449077/961516d4-f1e1-11e4-82fd-9bfcc151a804.png)

**Comment by nowned** [comment]
The original theme had really really silly container handling. I've gutted it and moved it to something much more logical.

It *could* have some negative effects somewhere on the site, but i've gone through every page type I can find and it all seems OK... So if you find anything weird, let me know!
